"""empty message

Revision ID: 9e8872dcf62f
Revises: 2f9d6d60edea
Create Date: 2020-11-28 15:13:06.690640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8872dcf62f'
down_revision = '2f9d6d60edea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Product_brand_key', 'Product', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Product_brand_key', 'Product', ['brand'])
    # ### end Alembic commands ###
